const QUESTION_BANK = {
  facil: [
    {
      pergunta: "Resolva: x + 4 = 10",
      alternativas: ["4", "5", "6", "7"],
      correta: 2,
      peso: 1,
      explicacao: "O +4 passa para o outro lado como -4.\nEntao fazemos 10 - 4.\n10 - 4 = 6.\nLogo, x = 6.",
    },
    {
      pergunta: "Resolva: x + 7 = 15",
      alternativas: ["6", "7", "8", "9"],
      correta: 2,
      peso: 1,
      explicacao: "O +7 passa para o outro lado como -7.\n15 - 7 = 8.\nLogo, x = 8.",
    },
    {
      pergunta: "Resolva: x + 9 = 20",
      alternativas: ["9", "10", "11", "12"],
      correta: 2,
      peso: 1,
      explicacao: "O +9 passa para o outro lado como -9.\n20 - 9 = 11.\nLogo, x = 11.",
    },
    {
      pergunta: "Resolva: x + 6 = 14",
      alternativas: ["6", "7", "8", "9"],
      correta: 2,
      peso: 1,
      explicacao: "O +6 passa para o outro lado como -6.\n14 - 6 = 8.\nLogo, x = 8.",
    },
    {
      pergunta: "Resolva: x + 3 = 18",
      alternativas: ["13", "14", "15", "16"],
      correta: 2,
      peso: 1,
      explicacao: "O +3 passa para o outro lado como -3.\n18 - 3 = 15.\nLogo, x = 15.",
    },
    {
      pergunta: "Resolva: x - 5 = 7",
      alternativas: ["10", "11", "12", "13"],
      correta: 2,
      peso: 1,
      explicacao: "O -5 passa para o outro lado como +5.\n7 + 5 = 12.\nLogo, x = 12.",
    },
    {
      pergunta: "Resolva: x - 8 = 4",
      alternativas: ["10", "11", "12", "13"],
      correta: 2,
      peso: 1,
      explicacao: "O -8 passa para o outro lado como +8.\n4 + 8 = 12.\nLogo, x = 12.",
    },
    {
      pergunta: "Resolva: x - 6 = 9",
      alternativas: ["13", "14", "15", "16"],
      correta: 2,
      peso: 1,
      explicacao: "O -6 passa para o outro lado como +6.\n9 + 6 = 15.\nLogo, x = 15.",
    },
    {
      pergunta: "Resolva: x + 2 = 9",
      alternativas: ["6", "7", "8", "9"],
      correta: 1,
      peso: 1,
      explicacao: "O +2 passa para o outro lado como -2.\n9 - 2 = 7.\nLogo, x = 7.",
    },
    {
      pergunta: "Resolva: x - 3 = 11",
      alternativas: ["12", "13", "14", "15"],
      correta: 1,
      peso: 1,
      explicacao: "O -3 passa para o outro lado como +3.\n11 + 3 = 14.\nLogo, x = 14.",
    },
    {
      pergunta: "Resolva: x + 5 = 13",
      alternativas: ["7", "8", "9", "10"],
      correta: 1,
      peso: 1,
      explicacao: "O +5 passa para o outro lado como -5.\n13 - 5 = 8.\nLogo, x = 8.",
    },
    {
      pergunta: "Resolva: x - 4 = 6",
      alternativas: ["8", "9", "10", "11"],
      correta: 2,
      peso: 1,
      explicacao: "O -4 passa para o outro lado como +4.\n6 + 4 = 10.\nLogo, x = 10.",
    },
    {
      pergunta: "Resolva: x + 8 = 17",
      alternativas: ["8", "9", "10", "11"],
      correta: 1,
      peso: 1,
      explicacao: "O +8 passa para o outro lado como -8.\n17 - 8 = 9.\nLogo, x = 9.",
    },
    {
      pergunta: "Resolva: x - 9 = 3",
      alternativas: ["10", "11", "12", "13"],
      correta: 2,
      peso: 1,
      explicacao: "O -9 passa para o outro lado como +9.\n3 + 9 = 12.\nLogo, x = 12.",
    },
    {
      pergunta: "Resolva: x + 1 = 5",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 1,
      explicacao: "O +1 passa para o outro lado como -1.\n5 - 1 = 4.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: x - 2 = 8",
      alternativas: ["9", "10", "11", "12"],
      correta: 1,
      peso: 1,
      explicacao: "O -2 passa para o outro lado como +2.\n8 + 2 = 10.\nLogo, x = 10.",
    },
    {
      pergunta: "Resolva: x + 10 = 19",
      alternativas: ["7", "8", "9", "10"],
      correta: 2,
      peso: 1,
      explicacao: "O +10 passa para o outro lado como -10.\n19 - 10 = 9.\nLogo, x = 9.",
    },
    {
      pergunta: "Resolva: x - 7 = 2",
      alternativas: ["7", "8", "9", "10"],
      correta: 2,
      peso: 1,
      explicacao: "O -7 passa para o outro lado como +7.\n2 + 7 = 9.\nLogo, x = 9.",
    },
    {
      pergunta: "Resolva: x + 12 = 20",
      alternativas: ["6", "7", "8", "9"],
      correta: 2,
      peso: 1,
      explicacao: "O +12 passa para o outro lado como -12.\n20 - 12 = 8.\nLogo, x = 8.",
    },
    {
      pergunta: "Resolva: x - 1 = 14",
      alternativas: ["13", "14", "15", "16"],
      correta: 2,
      peso: 1,
      explicacao: "O -1 passa para o outro lado como +1.\n14 + 1 = 15.\nLogo, x = 15.",
    },
    {
      pergunta: "Resolva: x + 11 = 25",
      alternativas: ["12", "13", "14", "15"],
      correta: 2,
      peso: 1,
      explicacao: "O +11 passa para o outro lado como -11.\n25 - 11 = 14.\nLogo, x = 14.",
    },
    {
      pergunta: "Resolva: x - 10 = 5",
      alternativas: ["14", "15", "16", "17"],
      correta: 1,
      peso: 1,
      explicacao: "O -10 passa para o outro lado como +10.\n5 + 10 = 15.\nLogo, x = 15.",
    },
    {
      pergunta: "Resolva: x + 13 = 30",
      alternativas: ["15", "16", "17", "18"],
      correta: 2,
      peso: 1,
      explicacao: "O +13 passa para o outro lado como -13.\n30 - 13 = 17.\nLogo, x = 17.",
    },
    {
      pergunta: "Resolva: x - 12 = 6",
      alternativas: ["16", "17", "18", "19"],
      correta: 2,
      peso: 1,
      explicacao: "O -12 passa para o outro lado como +12.\n6 + 12 = 18.\nLogo, x = 18.",
    },
    {
      pergunta: "Resolva: x + 15 = 28",
      alternativas: ["11", "12", "13", "14"],
      correta: 2,
      peso: 1,
      explicacao: "O +15 passa para o outro lado como -15.\n28 - 15 = 13.\nLogo, x = 13.",
    },
    {
      pergunta: "Resolva: x - 14 = 9",
      alternativas: ["21", "22", "23", "24"],
      correta: 2,
      peso: 1,
      explicacao: "O -14 passa para o outro lado como +14.\n9 + 14 = 23.\nLogo, x = 23.",
    },
    {
      pergunta: "Resolva: x + 16 = 40",
      alternativas: ["22", "23", "24", "25"],
      correta: 2,
      peso: 1,
      explicacao: "O +16 passa para o outro lado como -16.\n40 - 16 = 24.\nLogo, x = 24.",
    },
    {
      pergunta: "Resolva: x - 15 = 10",
      alternativas: ["23", "24", "25", "26"],
      correta: 2,
      peso: 1,
      explicacao: "O -15 passa para o outro lado como +15.\n10 + 15 = 25.\nLogo, x = 25.",
    },
    {
      pergunta: "Resolva: x + 18 = 27",
      alternativas: ["7", "8", "9", "10"],
      correta: 2,
      peso: 1,
      explicacao: "O +18 passa para o outro lado como -18.\n27 - 18 = 9.\nLogo, x = 9.",
    },
    {
      pergunta: "Resolva: x - 16 = 4",
      alternativas: ["18", "19", "20", "21"],
      correta: 2,
      peso: 1,
      explicacao: "O -16 passa para o outro lado como +16.\n4 + 16 = 20.\nLogo, x = 20.",
    },
  ],
  medio: [
    {
      pergunta: "Resolva: 2x + 4 = 12",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 2,
      explicacao: "O +4 passa para o outro lado como -4.\n12 - 4 = 8.\nAgora temos 2x = 8.\nO 2 que esta multiplicando passa dividindo.\n8 / 2 = x.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 3x + 6 = 21",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O +6 passa como -6.\n21 - 6 = 15.\nFica 3x = 15.\no 3 esta multiplicando e passa dividindo\n15 / 3 = x.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 4x + 8 = 24",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 2,
      explicacao: "O +8 passa como -8.\n24 - 8 = 16.\nTemos 4x = 16.\no 4 esta multiplicando e passa dividindo\n16 / 4 = x.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 5x + 5 = 30",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O +5 passa como -5.\n30 - 5 = 25.\n5x = 25.\no 5 esta multiplicando e passa dividindo\n25 / 5 = x.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 2x - 6 = 10",
      alternativas: ["6", "7", "8", "9"],
      correta: 2,
      peso: 2,
      explicacao: "O -6 passa como +6.\n10 + 6 = 16.\n2x = 16.\no 2 esta multiplicando e passa dividindo\n16 / 2 = x.\nLogo, x = 8.",
    },
    {
      pergunta: "Resolva: 3x - 9 = 6",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O -9 passa como +9.\n6 + 9 = 15.\n3x = 15.\no 3 esta multiplicando e passa dividindo\n15 / 3 = x.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 4x - 4 = 12",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 2,
      explicacao: "O -4 passa como +4.\n12 + 4 = 16.\n4x = 16.\no 4 esta multiplicando e passa dividindo\n16 / 4 = x.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 6x + 3 = 27",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 2,
      explicacao: "O +3 passa como -3.\n27 - 3 = 24.\n6x = 24.\no 6 esta multiplicando e passa dividindo\nx = 24 / 6.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 7x + 7 = 42",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O +7 passa como -7.\n42 - 7 = 35.\n7x = 35.\no 7 esta multiplicando e passa dividindo\nx = 35 / 7.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 8x + 4 = 36",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 2,
      explicacao: "O +4 passa como -4.\n36 - 4 = 32.\n8x = 32.\no 8 esta multiplicando e passa dividindo\nx = 32 / 8.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 2x + 9 = 17",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 2,
      explicacao: "O +9 passa como -9.\n17 - 9 = 8.\n2x = 8.\no 2 esta multiplicando e passa dividindo\nx = 8 / 2.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 3x + 12 = 27",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O +12 passa como -12.\n27 - 12 = 15.\n3x = 15.\no 3 esta multiplicando e passa dividindo\nx = 15 / 3.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 5x - 10 = 15",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O -10 passa como +10.\n15 + 10 = 25.\n5x = 25.\no 5 esta multiplicando e passa dividindo\nx = 25 / 5.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 9x - 9 = 18",
      alternativas: ["2", "3", "4", "5"],
      correta: 1,
      peso: 2,
      explicacao: "O -9 passa como +9.\n18 + 9 = 27.\n9x = 27.\no 9 esta multiplicando e passa dividindo\nx = 27 / 9.\nLogo, x = 3.",
    },
    {
      pergunta: "Resolva: 4x + 2 = 18",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 2,
      explicacao: "O +2 passa como -2.\n18 - 2 = 16.\n4x = 16.\no 4 esta multiplicando e passa dividindo\nx = 16 / 4.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 6x - 12 = 24",
      alternativas: ["4", "5", "6", "7"],
      correta: 2,
      peso: 2,
      explicacao: "O -12 passa como +12.\n24 + 12 = 36.\n6x = 36.\no 6 esta multiplicando e passa dividindo\nx = 36 / 6.\nLogo, x = 6.",
    },
    {
      pergunta: "Resolva: 7x - 14 = 21",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O -14 passa como +14.\n21 + 14 = 35.\n7x = 35.\no 7 esta multiplicando e passa dividindo\nx = 35 / 7.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 10x + 5 = 55",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O +5 passa como -5.\n55 - 5 = 50.\n10x = 50.\no 10 esta multiplicando e passa dividindo\nx = 50 / 10.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 12x - 6 = 30",
      alternativas: ["2", "3", "4", "5"],
      correta: 1,
      peso: 2,
      explicacao: "O -6 passa como +6.\n30 + 6 = 36.\n12x = 36.\no 12 esta multiplicando e passa dividindo\nx = 36 / 12 .\nLogo, x = 3.",
    },
    {
      pergunta: "Resolva: 15x + 5 = 80",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 2,
      explicacao: "O +5 passa como -5.\n80 - 5 = 75.\n15x = 75.\no 15 esta multiplicando e passa dividindo\nx = 75 / 15.\nLogo, x = 5.",
    },
  ],
  dificil: [
    {
      pergunta: "Resolva: 2(x + 3) = 14",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 3,
      explicacao: "Aplicamos a distributiva.\n2x + 6 = 14.\nO +6 passa como -6.\n14 - 6 = 8.\n2x = 8.\nx = 8 / 2.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 3(x - 2) = 21",
      alternativas: ["7", "8", "9", "10"],
      correta: 2,
      peso: 3,
      explicacao: "Aplicamos a distributiva.\n3x - 6 = 21.\nO -6 passa como +6.\n21 + 6 = 27.\n3x = 27.\nx = 27 / 3.\nLogo, x = 9.",
    },
    {
      pergunta: "Resolva: 4x + 5 = 2x + 17",
      alternativas: ["5", "6", "7", "8"],
      correta: 1,
      peso: 3,
      explicacao: "Passamos o 2x para o lado esquerdo como -2x.\n4x - 2x + 5 = 17.\n2x + 5 = 17.\nO +5 passa como -5.\n17 - 5 = 12.\n2x = 12.\nx = 12 / 2.\nLogo, x = 6.",
    },
    {
      pergunta: "Resolva: 5x - 3 = 2x + 12",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 3,
      explicacao: "Passamos o 2x para o lado esquerdo como -2x.\n5x - 2x - 3 = 12.\n3x - 3 = 12.\nO -3 passa como +3.\n12 + 3 = 15.\n3x = 15.\nx = 15 / 3 .\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 6(x + 1) = 3x + 18",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 3,
      explicacao: "Aplicamos a distributiva.\n6x + 6 = 3x + 18.\nPassamos o 3x para o lado esquerdo como -3x.\n6x - 3x + 6 = 18.\n3x + 6 = 18.\nO +6 passa como -6.\n18 - 6 = 12.\n3x = 12.\nx = 12 / 3.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 8x - 4 = 4x + 20",
      alternativas: ["5", "6", "7", "8"],
      correta: 1,
      peso: 3,
      explicacao: "Passamos o 4x para o lado esquerdo.\n8x - 4x - 4 = 20.\n4x - 4 = 20.\nO -4 passa como +4.\n20 + 4 = 24.\n4x = 24.\nx = 24 / 4.\nLogo, x = 6.",
    },
    {
      pergunta: "Resolva: 2(x - 5) + 4 = 18",
      alternativas: ["8", "9", "10", "12"],
      correta: 3,
      peso: 3,
      explicacao: "Aplicamos a distributiva.\n2x - 10 + 4 = 18.\n-10 + 4 = -6.\nFica 2x - 6 = 18.\nO -6 passa como +6.\n18 + 6 = 24.\n2x = 24.\nx = 24 / 2.\nLogo, x = 12.",
    },
    {
      pergunta: "Resolva: 3(x + 4) - 6 = 21",
      alternativas: ["4", "5", "6", "7"],
      correta: 1,
      peso: 3,
      explicacao: "Aplicamos a distributiva.\n3x + 12 - 6 = 21.\n12 - 6 = 6.\nFica 3x + 6 = 21.\nO +6 passa como -6.\n21 - 6 = 15.\n3x = 15.\nx = 15 / 3.\nLogo, x = 5.",
    },
    {
      pergunta: "Resolva: 9x + 3 = 3x + 27",
      alternativas: ["3", "4", "5", "6"],
      correta: 1,
      peso: 3,
      explicacao: "Passamos o 3x para o lado esquerdo.\n9x - 3x + 3 = 27.\n6x + 3 = 27.\nO +3 passa como -3.\n27 - 3 = 24.\n6x = 24.\nx = 24 / 6.\nLogo, x = 4.",
    },
    {
      pergunta: "Resolva: 4(x - 2) = 2(x + 6)",
      alternativas: ["4", "5", "6", "7"],
      correta: 2,
      peso: 3,
      explicacao: "Aplicamos a distributiva nos dois lados.\n4x - 8 = 2x + 12.\nPassamos o 2x para o lado esquerdo.\n4x - 2x - 8 = 12.\n2x - 8 = 12.\nO -8 passa como +8.\n12 + 8 = 20.\n2x = 20.\nx = 20 / 2.\nLogo, x = 10.",
    },
  ],
};

export default QUESTION_BANK;
